/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;
import Controle.MenuHandler;
import Modelo.Menu;
import java.util.Observable;
import java.util.Observer;


/**
 *
 * @author Tony
 */
public class JMenu extends javax.swing.JFrame implements Observer {
    
    MenuHandler h;
    Menu modelo;
    
    /**
     * Creates new form Principal
     */
    public JMenu(MenuHandler h, Menu modelo) {
        this.h=h;
        this.modelo = modelo;
        initComponents();
        setNames();
        modelo.addObserver(this);
        update(modelo, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTítulo = new javax.swing.JLabel();
        jLabelJogos = new javax.swing.JLabel();
        jLabelFichasECadastro = new javax.swing.JLabel();
        jButtonRoleta = new javax.swing.JButton();
        jButtonCacaNiqueis = new javax.swing.JButton();
        jButtonVinteeUm = new javax.swing.JButton();
        jButtonLoja = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonInstrucoes = new javax.swing.JButton();
        jButtonJogadores = new javax.swing.JButton();
        jSeparatorCima = new javax.swing.JSeparator();
        jSeparatorBaixo = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTítulo.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabelTítulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTítulo.setText("Cassino ");

        jLabelJogos.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        jLabelJogos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJogos.setText("Jogos");

        jLabelFichasECadastro.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        jLabelFichasECadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFichasECadastro.setText("Fichas           Cadastro");

        jButtonRoleta.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jButtonRoleta.setText("Roleta");
        jButtonRoleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MousePressed(evt);
            }
        });

        jButtonCacaNiqueis.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jButtonCacaNiqueis.setText("Caça-Níquel");
        jButtonCacaNiqueis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MousePressed(evt);
            }
        });

        jButtonVinteeUm.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jButtonVinteeUm.setText("Vinte e Um");
        jButtonVinteeUm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MousePressed(evt);
            }
        });

        jButtonLoja.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jButtonLoja.setText("Loja");
        jButtonLoja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MousePressed(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonSairMousePressed(evt);
            }
        });

        jButtonInstrucoes.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jButtonInstrucoes.setText("Instruções");
        jButtonInstrucoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MousePressed(evt);
            }
        });

        jButtonJogadores.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jButtonJogadores.setText("Jogadores");
        jButtonJogadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorCima)
                    .addComponent(jLabelTítulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRoleta, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCacaNiqueis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonVinteeUm, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelFichasECadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jButtonLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addComponent(jSeparatorBaixo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonInstrucoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSair)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelJogos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCacaNiqueis, jButtonRoleta, jButtonVinteeUm});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTítulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorCima, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelJogos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCacaNiqueis)
                    .addComponent(jButtonVinteeUm)
                    .addComponent(jButtonRoleta))
                .addGap(34, 34, 34)
                .addComponent(jLabelFichasECadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLoja)
                    .addComponent(jButtonJogadores))
                .addGap(43, 43, 43)
                .addComponent(jSeparatorBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSair)
                    .addComponent(jButtonInstrucoes))
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCacaNiqueis, jButtonLoja, jButtonRoleta, jButtonSair, jButtonVinteeUm});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButtonSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSairMousePressed

    private void MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MousePressed
        // TODO add your handling code here:
        h.mousePressed(evt);
    }//GEN-LAST:event_MousePressed

    /**
     * @param args the command line arguments
     */    
    public void setNames(){
        jButtonInstrucoes.setName("Instrucoes");
        jButtonLoja.setName("Loja");
        jButtonJogadores.setName("Cadastro");
        jButtonVinteeUm.setName("21");
        jButtonCacaNiqueis.setName("Jackpot");
        jButtonRoleta.setName("Roleta");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCacaNiqueis;
    private javax.swing.JButton jButtonInstrucoes;
    private javax.swing.JButton jButtonJogadores;
    private javax.swing.JButton jButtonLoja;
    private javax.swing.JButton jButtonRoleta;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonVinteeUm;
    private javax.swing.JLabel jLabelFichasECadastro;
    private javax.swing.JLabel jLabelJogos;
    private javax.swing.JLabel jLabelTítulo;
    private javax.swing.JSeparator jSeparatorBaixo;
    private javax.swing.JSeparator jSeparatorCima;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable arg0, Object arg1) {
        this.setVisible(modelo.isVisible());
        this.setEnabled(modelo.isVisible());
    }
}
