/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;
import Controle.RoletaHandler;
import Modelo.FichasInsuficientesException;
import Modelo.Roleta;
import java.awt.Color;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Tony
 */
public class JRoleta extends javax.swing.JFrame implements Observer {

    RoletaHandler h;
    JMenu menu;
    JInstrucoesRoleta instrucoes;
    Roleta roleta;
    
    /**
     * Creates new form JRoleta
     */
    public JRoleta(RoletaHandler h, JMenu menu, Roleta roleta) {
        this.h = h;
        this.menu = menu;
        instrucoes = new JInstrucoesRoleta(h, roleta);
        this.roleta=roleta;
        initComponents();
        jButtonMenu.setName("Menu");
        jButtonRegras.setName("Regras");
        roleta.addObserver(this);
        update(roleta,this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTítulo = new javax.swing.JLabel();
        jSeparatorBaixo = new javax.swing.JSeparator();
        jSeparatorCima = new javax.swing.JSeparator();
        jButtonRegras = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jButton1Vermelho = new javax.swing.JButton();
        jButton2Vermelho = new javax.swing.JButton();
        jButton3Vermelho = new javax.swing.JButton();
        jButton4Vermelho = new javax.swing.JButton();
        jButton5Vermelho = new javax.swing.JButton();
        jButton6Vermelho = new javax.swing.JButton();
        jButton7Vermelho = new javax.swing.JButton();
        jButton8Vermelho = new javax.swing.JButton();
        jButton9Vermelho = new javax.swing.JButton();
        jButton10Vermelho = new javax.swing.JButton();
        jButton11Vermelho = new javax.swing.JButton();
        jButton12Vermelho = new javax.swing.JButton();
        jButton13Vermelho = new javax.swing.JButton();
        jButton14Vermelho = new javax.swing.JButton();
        jButton15Vermelho = new javax.swing.JButton();
        jButton16Vermelho = new javax.swing.JButton();
        jButton17Vermelho = new javax.swing.JButton();
        jButton18Vermelho = new javax.swing.JButton();
        jButton16Preto = new javax.swing.JButton();
        jButton17Preto = new javax.swing.JButton();
        jButton18Preto = new javax.swing.JButton();
        jButton1Preto = new javax.swing.JButton();
        jButton2Preto = new javax.swing.JButton();
        jButton3Preto = new javax.swing.JButton();
        jButton4Preto = new javax.swing.JButton();
        jButton5Preto = new javax.swing.JButton();
        jButton6Preto = new javax.swing.JButton();
        jButton7Preto = new javax.swing.JButton();
        jButton8Preto = new javax.swing.JButton();
        jButton9Preto = new javax.swing.JButton();
        jButton10Preto = new javax.swing.JButton();
        jButton11Preto = new javax.swing.JButton();
        jButton12Preto = new javax.swing.JButton();
        jButton13Preto = new javax.swing.JButton();
        jButton14Preto = new javax.swing.JButton();
        jButton15Preto = new javax.swing.JButton();
        jLabelNumeroSorteado = new javax.swing.JLabel();
        jButtonNumeroSorteado = new javax.swing.JButton();
        jRadioButtonNumero = new javax.swing.JRadioButton();
        jRadioButtonCor = new javax.swing.JRadioButton();
        jRadioButtonCoreNumero = new javax.swing.JRadioButton();
        jLabelApostaRealizada = new javax.swing.JLabel();
        jLabelCor = new javax.swing.JLabel();
        jTextFieldCor = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelValorDeAposta = new javax.swing.JLabel();
        jTextFieldValorDeAposta = new javax.swing.JTextField();
        jLabelJogadorAtual = new javax.swing.JLabel();
        jButtonSortear = new javax.swing.JButton();
        jButtonProximoJogador = new javax.swing.JButton();
        jLabelFichasJogadorAtual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTítulo.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabelTítulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTítulo.setText("Roleta");

        jButtonRegras.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jButtonRegras.setText("Regras");
        jButtonRegras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JRoleta.this.mousePressed(evt);
            }
        });

        jButtonMenu.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jButtonMenu.setText("Menu");
        jButtonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JRoleta.this.mousePressed(evt);
            }
        });

        jButton1Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton1Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton1Vermelho.setText("1");

        jButton2Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton2Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton2Vermelho.setText("2");

        jButton3Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton3Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton3Vermelho.setText("3");

        jButton4Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton4Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton4Vermelho.setText("4");

        jButton5Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton5Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton5Vermelho.setText("5");

        jButton6Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton6Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton6Vermelho.setText("6");

        jButton7Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton7Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton7Vermelho.setText("7");

        jButton8Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton8Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton8Vermelho.setText("8");

        jButton9Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton9Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton9Vermelho.setText("9");

        jButton10Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton10Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton10Vermelho.setText("10");

        jButton11Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton11Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton11Vermelho.setText("11");

        jButton12Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton12Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton12Vermelho.setText("12");

        jButton13Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton13Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton13Vermelho.setText("13");

        jButton14Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton14Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton14Vermelho.setText("14");

        jButton15Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton15Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton15Vermelho.setText("15");

        jButton16Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton16Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton16Vermelho.setText("16");

        jButton17Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton17Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton17Vermelho.setText("17");

        jButton18Vermelho.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton18Vermelho.setForeground(new java.awt.Color(255, 0, 0));
        jButton18Vermelho.setText("18");

        jButton16Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton16Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton16Preto.setText("16");

        jButton17Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton17Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton17Preto.setText("17");

        jButton18Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton18Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton18Preto.setText("18");

        jButton1Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton1Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton1Preto.setText("1");

        jButton2Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton2Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton2Preto.setText("2");

        jButton3Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton3Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton3Preto.setText("3");

        jButton4Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton4Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton4Preto.setText("4");

        jButton5Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton5Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton5Preto.setText("5");

        jButton6Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton6Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton6Preto.setText("6");

        jButton7Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton7Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton7Preto.setText("7");

        jButton8Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton8Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton8Preto.setText("8");

        jButton9Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton9Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton9Preto.setText("9");

        jButton10Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton10Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton10Preto.setText("10");

        jButton11Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton11Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton11Preto.setText("11");

        jButton12Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton12Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton12Preto.setText("12");

        jButton13Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton13Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton13Preto.setText("13");

        jButton14Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton14Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton14Preto.setText("14");

        jButton15Preto.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButton15Preto.setForeground(new java.awt.Color(5, 0, 0));
        jButton15Preto.setText("15");

        jLabelNumeroSorteado.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabelNumeroSorteado.setText("Número sorteado:");

        jButtonNumeroSorteado.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButtonNumeroSorteado.setForeground(new java.awt.Color(255, 0, 0));
        jButtonNumeroSorteado.setMaximumSize(new java.awt.Dimension(46, 16));
        jButtonNumeroSorteado.setMinimumSize(new java.awt.Dimension(46, 16));
        jButtonNumeroSorteado.setPreferredSize(new java.awt.Dimension(46, 16));

        jRadioButtonNumero.setText("Número");
        jRadioButtonNumero.setName("numero"); // NOI18N
        jRadioButtonNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JRoleta.this.mousePressed(evt);
            }
        });

        jRadioButtonCor.setText("Cor");
        jRadioButtonCor.setName("cor"); // NOI18N
        jRadioButtonCor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JRoleta.this.mousePressed(evt);
            }
        });

        jRadioButtonCoreNumero.setText("Cor e Número");
        jRadioButtonCoreNumero.setName("corNumero"); // NOI18N
        jRadioButtonCoreNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JRoleta.this.mousePressed(evt);
            }
        });

        jLabelApostaRealizada.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabelApostaRealizada.setText("Qual aposta será realizada?");

        jLabelCor.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabelCor.setText("Cor");

        jTextFieldCor.setName("cor"); // NOI18N
        jTextFieldCor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCorKeyReleased(evt);
            }
        });

        jLabelNumero.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabelNumero.setText("Número");

        jTextFieldNumero.setName("numero"); // NOI18N
        jTextFieldNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyReleased(evt);
            }
        });

        jLabelValorDeAposta.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabelValorDeAposta.setText("Valor de aposta");

        jTextFieldValorDeAposta.setName("aposta"); // NOI18N
        jTextFieldValorDeAposta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldValorDeApostaKeyReleased(evt);
            }
        });

        jLabelJogadorAtual.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabelJogadorAtual.setText("Jogador 0");

        jButtonSortear.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jButtonSortear.setText("Sortear");
        jButtonSortear.setName("sortear"); // NOI18N
        jButtonSortear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JRoleta.this.mousePressed(evt);
            }
        });

        jButtonProximoJogador.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jButtonProximoJogador.setText("Próximo Jogador");
        jButtonProximoJogador.setName("proximo"); // NOI18N
        jButtonProximoJogador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JRoleta.this.mousePressed(evt);
            }
        });

        jLabelFichasJogadorAtual.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabelFichasJogadorAtual.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonRegras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonProximoJogador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMenu))
                    .addComponent(jSeparatorBaixo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelJogadorAtual)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparatorCima, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton7Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1Preto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13Vermelho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton8Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton14Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton14Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton15Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton15Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton10Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton16Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton16Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton11Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton17Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton17Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton12Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton18Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton18Preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabelApostaRealizada)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelNumeroSorteado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jRadioButtonCor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonNumero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonCoreNumero)
                                        .addGap(13, 13, 13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabelCor)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabelNumero)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButtonSortear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabelValorDeAposta))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(jTextFieldValorDeAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(32, 32, 32))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelFichasJogadorAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTítulo, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTítulo)
                        .addComponent(jLabelFichasJogadorAtual))
                    .addComponent(jLabelJogadorAtual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorCima, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1Vermelho)
                            .addComponent(jButton2Vermelho)
                            .addComponent(jButton3Vermelho)
                            .addComponent(jButton4Vermelho)
                            .addComponent(jButton5Vermelho)
                            .addComponent(jButton6Vermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7Vermelho)
                            .addComponent(jButton8Vermelho)
                            .addComponent(jButton9Vermelho)
                            .addComponent(jButton10Vermelho)
                            .addComponent(jButton11Vermelho)
                            .addComponent(jButton12Vermelho)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelApostaRealizada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonNumero)
                            .addComponent(jRadioButtonCor)
                            .addComponent(jRadioButtonCoreNumero))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelCor)
                                .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelValorDeAposta))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelNumero)
                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldValorDeAposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonSortear))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton14Vermelho)
                                .addComponent(jButton15Vermelho)
                                .addComponent(jButton16Vermelho)
                                .addComponent(jButton17Vermelho)
                                .addComponent(jButton18Vermelho)
                                .addComponent(jButton13Vermelho))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1Preto)
                                .addComponent(jButton2Preto)
                                .addComponent(jButton3Preto)
                                .addComponent(jButton4Preto)
                                .addComponent(jButton5Preto)
                                .addComponent(jButton6Preto))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton7Preto)
                                .addComponent(jButton8Preto)
                                .addComponent(jButton9Preto)
                                .addComponent(jButton10Preto)
                                .addComponent(jButton11Preto)
                                .addComponent(jButton12Preto))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton14Preto)
                                .addComponent(jButton15Preto)
                                .addComponent(jButton16Preto)
                                .addComponent(jButton17Preto)
                                .addComponent(jButton18Preto)
                                .addComponent(jButton13Preto)
                                .addComponent(jLabelNumeroSorteado))))
                    .addComponent(jButtonNumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMenu)
                    .addComponent(jButtonRegras)
                    .addComponent(jButtonProximoJogador))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCorKeyReleased
        h.keyReleased(evt);
    }//GEN-LAST:event_jTextFieldCorKeyReleased

    private void jTextFieldNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyReleased
        try{
            h.keyReleased(evt);
        }catch(Exception e){} //Evitando o erro de String pra numero 
                            // -> assumindo que so vai digitar numero, ta na instrucao
    }//GEN-LAST:event_jTextFieldNumeroKeyReleased

    private void jTextFieldValorDeApostaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorDeApostaKeyReleased
        try{
            h.keyReleased(evt);
        }catch(Exception e){} //Evitando o erro de String pra numero 
                              //-> assumindo que so vai digitar numero, ta na instrucao
    }//GEN-LAST:event_jTextFieldValorDeApostaKeyReleased

    private void mousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousePressed
        try {
            // TODO add your handling code here:
            h.mousePressedd(evt);
        } catch (FichasInsuficientesException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), 
                            "Fichas Insuficientes", JOptionPane.ERROR_MESSAGE);        
        }
    }//GEN-LAST:event_mousePressed

    private void atualizarJogadorAtualRoleta(){
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10Preto;
    private javax.swing.JButton jButton10Vermelho;
    private javax.swing.JButton jButton11Preto;
    private javax.swing.JButton jButton11Vermelho;
    private javax.swing.JButton jButton12Preto;
    private javax.swing.JButton jButton12Vermelho;
    private javax.swing.JButton jButton13Preto;
    private javax.swing.JButton jButton13Vermelho;
    private javax.swing.JButton jButton14Preto;
    private javax.swing.JButton jButton14Vermelho;
    private javax.swing.JButton jButton15Preto;
    private javax.swing.JButton jButton15Vermelho;
    private javax.swing.JButton jButton16Preto;
    private javax.swing.JButton jButton16Vermelho;
    private javax.swing.JButton jButton17Preto;
    private javax.swing.JButton jButton17Vermelho;
    private javax.swing.JButton jButton18Preto;
    private javax.swing.JButton jButton18Vermelho;
    private javax.swing.JButton jButton1Preto;
    private javax.swing.JButton jButton1Vermelho;
    private javax.swing.JButton jButton2Preto;
    private javax.swing.JButton jButton2Vermelho;
    private javax.swing.JButton jButton3Preto;
    private javax.swing.JButton jButton3Vermelho;
    private javax.swing.JButton jButton4Preto;
    private javax.swing.JButton jButton4Vermelho;
    private javax.swing.JButton jButton5Preto;
    private javax.swing.JButton jButton5Vermelho;
    private javax.swing.JButton jButton6Preto;
    private javax.swing.JButton jButton6Vermelho;
    private javax.swing.JButton jButton7Preto;
    private javax.swing.JButton jButton7Vermelho;
    private javax.swing.JButton jButton8Preto;
    private javax.swing.JButton jButton8Vermelho;
    private javax.swing.JButton jButton9Preto;
    private javax.swing.JButton jButton9Vermelho;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonNumeroSorteado;
    private javax.swing.JButton jButtonProximoJogador;
    private javax.swing.JButton jButtonRegras;
    private javax.swing.JButton jButtonSortear;
    private javax.swing.JLabel jLabelApostaRealizada;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelFichasJogadorAtual;
    private javax.swing.JLabel jLabelJogadorAtual;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelNumeroSorteado;
    private javax.swing.JLabel jLabelTítulo;
    private javax.swing.JLabel jLabelValorDeAposta;
    private javax.swing.JRadioButton jRadioButtonCor;
    private javax.swing.JRadioButton jRadioButtonCoreNumero;
    private javax.swing.JRadioButton jRadioButtonNumero;
    private javax.swing.JSeparator jSeparatorBaixo;
    private javax.swing.JSeparator jSeparatorCima;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldValorDeAposta;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        
        this.setVisible(roleta.isVisible());
        if(this.isVisible()){
            jLabelJogadorAtual.setText(roleta.getNomeJogadorAtual());
            jLabelFichasJogadorAtual.setText("Fichas: " + roleta.getFichasJogadorAtual());    
        }
        String num = Integer.toString(roleta.getNumeroAtual());
        jButtonNumeroSorteado.setText(num);
        String cor = "";
        cor += roleta.getCorAtual();
        Color c;
        if(cor.equals("preto"))
            c = new Color(0,0,0);
        else
            c = new Color((int)255,(int)0,(int)0);
        jButtonNumeroSorteado.setForeground(c);        
    }
}
